# Generated by Django 3.0.8 on 2020-07-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='All_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyname', models.CharField(max_length=200)),
                ('authorname', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_form.Content_Type')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_form.Content_Edition')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_form.Content_Year')),
            ],
        ),
    ]
