# Generated by Django 3.0.8 on 2020-07-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_form', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
