# Generated by Django 3.0.8 on 2020-07-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_form', '0002_auto_20200720_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
