# Generated by Django 3.0.8 on 2020-07-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_form', '0003_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_fields',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
