# Generated by Django 3.0.8 on 2020-07-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_form', '0004_all_fields_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_fields',
            name='image',
        ),
    ]
