# Generated by Django 3.0.8 on 2020-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_form', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authImg', models.ImageField(blank=True, upload_to='authimgs')),
                ('authName', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='all_fields',
            name='uniqueID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
