# Generated by Django 3.0.8 on 2020-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_form', '0005_auto_20200816_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='authdetails',
            name='uID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
